<?php
/**
 * CurlTest 2
 * 
 * Original testing for connecting to Booker API via Curl with PHP
 *
 * Codes and Keys stored commented here:
 * $OASKey = 'fe2de837b6624c91a93e36350743e223';
 * $grantstring = "grant_type=client_credentials&client_id=wjfobeqQUIsQ&client_secret=7HcPPOhErNE1&scope=customer";
 */ 

$client_id = 'wjfobeqQUIsQ';
$client_secret = '7HcPPOhErNE1';

/**
 * Step One - Obtain Token
 * Function createBookerToken to obtain an access token from Booker API
 * variable $cid     - Client ID, specific to each location
 * variable $csecret - Client Secret or Key, specific to each location
 */
function createBookerToken($cid, $csecret) {
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, 'https://api-staging.booker.com/v5/auth/connect/token');
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, sprintf("grant_type=client_credentials&client_id=%s&client_secret=%s&scope=customer", $cid, $csecret) );

    //if ($_SERVER['SERVER_NAME'] == 'localhost') {
    curl_setopt($ch, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);
    //}

    curl_setopt($ch, CURLOPT_POST, 1);
    $headers = array();
    $headers[] = 'Content-Type: application/x-www-form-urlencoded';
    $headers[] = 'Ocp-Apim-Subscription-Key: fe2de837b6624c91a93e36350743e223';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    } 
    curl_close($ch);
    return $result;
}
$tokenoutput = createBookerToken($client_id, $client_secret);
$token = json_decode($tokenoutput);
$sessiontoken = $token->access_token; //This value, once generated, is good for 30 minutes (1800 seconds)
print $sessiontoken;
echo "<hr>";

/**
 * Step Two - Use Find Locations classes to get STRING
 * Create JSON Object that has required Data Structure for FUNCTION findBookerLocation to use
 * Uses the $sessiontoken varible created by the execution of Step One above
 */
class sortLocationsBy {
    public $SortBy = 'Name';
    public $SortDirection = 0;
}

class findLocations {
    public $UsePaging = "";
    public $PageNumber = "";
    public $PageSize = "";

    public $SortBy = array();
    public function __construct(){
        array_push($this->SortBy, new sortLocationsBy);
    }
    public $access_token = "";
}
$p = new FindLocations();
$p->UsePaging = true;
$p->PageNumber = 1;
$p->PageSize = 20;
$p->access_token = $sessiontoken;

$pstring = json_encode($p);
//echo $pstring;
//echo "<hr><hr><hr>";
//--------------------Trying another option, and it WORKS!!!!!!!!    
//--------------------Trying another option, and it WORKS!!!!!!!!    



/**
 * Step Three - Find Location
 * Function findBookerLocation to obtain JSON data for location
 * $stringToPost - value generated by FindLocations CLASS executed in Step Two above
 */
function findBookerLocation($stringToPost) {
    $chloc = curl_init();
    curl_setopt($chloc, CURLOPT_URL, 'https://api-staging.booker.com/v4.1/customer/locations');
    curl_setopt($chloc, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($chloc, CURLOPT_POSTFIELDS, $stringToPost );

    //if ($_SERVER['SERVER_NAME'] == 'localhost') {
    curl_setopt($chloc, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($chloc, CURLOPT_SSL_VERIFYPEER, false);
    //}

    curl_setopt($chloc, CURLOPT_POST, 1);
    $locheaders = array();
    $locheaders[] = 'Content-Type: application/json';
    $locheaders[] = 'Ocp-Apim-Subscription-Key: fe2de837b6624c91a93e36350743e223';
    curl_setopt($chloc, CURLOPT_HTTPHEADER, $locheaders);
    $locresult = curl_exec($chloc);
    if (curl_errno($chloc)) {
        echo 'Error:' . curl_error($chloc);
    }
    curl_close($chloc);
    return $locresult;
}

$findlocation = findBookerLocation($pstring);
//$findlocation = findBookerLocation($sessiontoken);

$location = json_decode($findlocation);
//echo "<br><br>";
//var_dump($findlocation);
//echo "<hr>";

$location_zip = $location->Results[0]->Address->Zip; //returns 75024
$location_id =  $location->Results[0]->ID;

print $location_zip;
echo "<hr>";
print $location_id;
echo "<hr>";






class findTreatments {
    public $LocationID = "";
    public $UsePaging = "";
    public $PageNumber = "";
    public $PageSize = "";
    public $SortBy = array();
    public function __construct(){
        array_push($this->SortBy, new sortLocationsBy);
    }
    public $access_token = "";
}
$t = new FindTreatments();
$t->UsePaging = true;
$t->PageNumber = 1;
$t->PageSize = 20;
$t->access_token = $sessiontoken;
$t->LocationID = $location_id;

$tstring = json_encode($t);
echo $tstring;
echo "<hr><hr><hr>";

/**
 * Step Four - Find Treatments
 * Function findBookerTreatments to obtain JSON data for treatments by location
 * 
 */
function findBookerTreatments($stringToPost) {
    $chloc = curl_init();
    curl_setopt($chloc, CURLOPT_URL, 'https://api-staging.booker.com/v4.1/customer/treatments');
    curl_setopt($chloc, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($chloc, CURLOPT_POSTFIELDS, $stringToPost );

    //if ($_SERVER['SERVER_NAME'] == 'localhost') {
    curl_setopt($chloc, CURLOPT_SSL_VERIFYHOST, false);
    curl_setopt($chloc, CURLOPT_SSL_VERIFYPEER, false);
    //}

    curl_setopt($chloc, CURLOPT_POST, 1);
    $locheaders = array();
    $locheaders[] = 'Content-Type: application/json';
    $locheaders[] = 'Ocp-Apim-Subscription-Key: fe2de837b6624c91a93e36350743e223';
    curl_setopt($chloc, CURLOPT_HTTPHEADER, $locheaders);
    $locresult = curl_exec($chloc);
    if (curl_errno($chloc)) {
        echo 'Error:' . curl_error($chloc);
    }
    curl_close($chloc);
    return $locresult;
}

$showtreatments = findBookerTreatments($tstring);

$treatments = json_decode($showtreatments);
echo "<br><br>";
var_dump($showtreatments);